import { Platform, StyleSheet } from 'react-native';

export const SERIF = Platform.select({ ios: 'Georgia', android: 'serif', default: 'Georgia' });

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0a0a0a' },
  fill: { flex: 1 },

  topBar: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
  },
  eyebrow: {
    fontSize: 11,
    letterSpacing: 2.4,
    color: 'rgba(255,255,255,0.75)',
    fontWeight: '600',
  },

  stage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },

  cardWrap: {
    position: 'relative',
  },
  glow: {
    position: 'absolute',
    top: -20,
    left: -20,
    right: -20,
    bottom: -20,
    borderRadius: 28,
    backgroundColor: 'transparent',
    ...Platform.select({
      ios: {
        shadowColor: 'rgba(120,140,255,0.8)',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 30,
      },
      android: {
        elevation: 16,
      },
      default: {},
    }),
  },
  face: {
    flex: 1,
    width: '100%',
    height: '100%',
    borderRadius: 18,
    borderCurve: 'continuous',
    overflow: 'hidden',
    backgroundColor: '#0a0a0a',
    boxShadow: '0px 16px 28px rgba(0,0,0,0.45)',
  },
  imageRadius: {
    borderRadius: 18,
    borderCurve: 'continuous',
  },
  hintScrim: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
  },
  hint: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    color: 'rgba(255,255,255,0.85)',
    fontSize: 10,
    letterSpacing: 2.8,
    fontWeight: '600',
    textAlign: 'center',
    paddingVertical: 18,
  },
  hintBack: {
    position: 'relative',
    marginTop: 'auto',
    paddingTop: 24,
  },
  expandBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 34,
    height: 34,
    borderRadius: 17,
    borderCurve: 'continuous',
    backgroundColor: 'rgba(0,0,0,0.42)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.32)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  expandIcon: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 15,
    fontWeight: '600',
  },
  fallbackBadge: {
    position: 'absolute',
    top: 14,
    right: 14,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  fallbackBadgeText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 9,
    letterSpacing: 2,
    fontWeight: '600',
  },

  back: {
    flex: 1,
    padding: 26,
    justifyContent: 'flex-start',
  },
  backEyebrow: {
    fontSize: 10,
    letterSpacing: 2.8,
    color: 'rgba(255,255,255,0.5)',
    fontWeight: '600',
    marginBottom: 12,
  },
  common: {
    fontFamily: SERIF,
    fontSize: 32,
    lineHeight: 38,
    color: '#fff',
    letterSpacing: 0.2,
  },
  latin: {
    fontFamily: SERIF,
    fontStyle: 'italic',
    fontSize: 16,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 4,
    letterSpacing: 0.3,
  },
  rule: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.22)',
    marginTop: 18,
    marginBottom: 16,
    width: 56,
  },
  blurb: {
    fontSize: 15,
    lineHeight: 23,
    color: 'rgba(255,255,255,0.88)',
  },
  nav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 16,
    paddingTop: 12,
  },
  navBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.45)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  navBtnDisabled: { opacity: 0.25 },
  navLabel: {
    fontSize: 13,
    color: '#fff',
    letterSpacing: 0.3,
  },
  navSubtle: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: '600',
  },

  placeholder: {
    borderRadius: 18,
    borderCurve: 'continuous',
    backgroundColor: '#111',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  loadingLabel: {
    marginTop: 18,
    color: 'rgba(255,255,255,0.55)',
    fontSize: 11,
    letterSpacing: 2.4,
    fontWeight: '600',
  },
  errorTitle: {
    fontFamily: SERIF,
    fontSize: 22,
    lineHeight: 28,
    color: '#fff',
    textAlign: 'center',
  },
  errorSub: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
    marginTop: 10,
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: 320,
  },
  primaryBtn: {
    marginTop: 22,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  primaryBtnLabel: {
    color: '#0a0a0a',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0.4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#161616',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    width: '100%',
    maxWidth: 400,
    padding: 24,
    maxHeight: '80%',
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 16,
    textAlign: 'center',
  },
  overrideLabel: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    marginBottom: 4,
  },
  overrideStatus: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.4)',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 8,
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  chipSelected: {
    borderColor: '#fff',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  chipText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
  },
  chipTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  textInput: {
    flex: 1,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: '#111',
    color: '#fff',
    paddingHorizontal: 12,
    fontSize: 14,
  },
  applyBtn: {
    height: 44,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyBtnText: {
    color: '#000',
    fontWeight: '600',
    fontSize: 14,
  },
  dismissBtn: {
    marginTop: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  dismissBtnText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 1,
  },
  topBarRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 24,
  },
  searchBarBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    marginTop: 4,
  },
  searchBarBtnLabel: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1,
  },
  noResultsText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 20,
    paddingHorizontal: 12,
  },
  searchResultItem: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  searchResultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchResultCommon: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  searchResultMatch: {
    color: 'rgba(100,255,200,0.85)',
    fontSize: 12,
    fontWeight: '600',
  },
  searchResultLatin: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 2,
  },
  searchResultRegion: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 11,
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
